### ISSUE TITLE
Auto-Op on join

### ISSUE THREAD

**Issue by DaBoyTM** [IslandFreedom/IslandFreedomMod#1]
Like FOP, when someone join and they are not opped, it will auto-op them so they don't have to worry about saying things like 'Op?' 'GIVE ME THE MOTHERF***A OP!'

**Comment by tylerhyperHD** [comment]
All you need to do is type !op in chat and it will op you.

**Comment by AlexFreedomMod** [comment]
Yeah, we will need to add it to the player listener but I could do this in AlexUtilsMod.
