### ISSUE TITLE
Fixing /sys

### ISSUE THREAD

**Issue by LegendIsAwesomes** [IslandFreedom/IslandFreedomMod#2]
if (!TFM_Util.SYS_ADMINS.contains(sender.getName()) && !TFM_Util.IFM_DEVELOPERS.contains(sender.getName()) && !TotalFreedomMod.OWNER.contains(sender.getName()) && !TFM_Util.CO_OWNER.contains(sender.getName()))

Not totally sure if the code is correct BUT co owner needs be added to /sys for permissions to do so.

**Comment by AlexFreedomMod** [comment]
Owner and co owner should have it
